# Generated by Django 5.1.5 on 2025-02-03 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.user'),
        ),
    ]
